"use client";

import { useMemo } from "react";
import { motion } from "framer-motion";
import type { Transition } from "framer-motion";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatCurrency, formatDecimal } from "@/lib/formatters";
import { cn } from "@/lib/utils";
import { ScoreBadge } from "@/components/common/score-badge";
import { EntityAvatar } from "@/components/common/entity-avatar";
import { HelpTooltip } from "@/components/help/help-tooltip";
import { navigators } from "@/data/navigators";
import { pilots } from "@/data/pilots";
import { groups } from "@/data/groups";
import type { Trade } from "@/data/types";

const PANEL_TRANSITION: Transition = { duration: 0.28, ease: "easeOut" };

type TradeDetailDialogProps = {
  trade: Trade | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
};

export function TradeDetailDialog({ trade, open, onOpenChange }: TradeDetailDialogProps) {
  const navigator = useMemo(
    () => (trade ? navigators.find((item) => item.id === trade.navigatorId) ?? null : null),
    [trade],
  );
  const pilot = useMemo(
    () => (trade ? pilots.find((item) => item.id === trade.pilotId) ?? null : null),
    [trade],
  );
  const group = useMemo(
    () => (trade && trade.groupId ? groups.find((item) => item.id === trade.groupId) ?? null : null),
    [trade],
  );

  const durationMinutes = trade
    ? Math.max(
        1,
        Math.round(
          (new Date(trade.exitTime).getTime() - new Date(trade.entryTime).getTime()) /
            (1000 * 60),
        ),
      )
    : 0;

  const feePool = trade ? Math.max(0, trade.profit * 0.03) : 0;
  const navigatorFee = feePool * 0.5;
  const pilotFee = feePool * 0.25;
  const brokerFee = feePool * 0.25;

  const profitTone = trade && trade.profit >= 0 ? "text-primary" : "text-[color:var(--pilot-bad)]";

  const riskBadgeTone = trade?.riskFlag && trade.riskFlag !== "none" ? "bad" : "good";

  const sectionHelp = {
    Execution: "Entry/exit pricing, timestamps, and duration so you can narrate the full lifecycle of this trade.",
    Participants: "Shows which navigator, pilot, and group are tied to the execution for quick follow-up.",
    "Fee Breakdown": "3% fee pool split across navigator, pilot, and broker based on the trade’s profit.",
    "Risk & Compliance": "Risk flag context so you can explain compliance posture for this execution.",
    "Next Steps": "Notes on upcoming enhancements or follow-ups related to this trade.",
  } as const;

  const tradeMetricHelp = {
    "Entry Price": "Price at which the navigator entered; paired with exit to show trade edge.",
    "Exit Price": "Price at which the position was closed.",
    "Entry Time": "Timestamp when the trade opened.",
    "Exit Time": "Timestamp when the trade closed.",
    Duration: "Elapsed minutes between entry and exit.",
    Group: "Group allocation the trade rolled up to for analytics.",
    Profit: "Net profit or loss generated by this trade.",
    "3% Fee": "Policy-level fee pool calculated as 3% of profit.",
  } as const;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="w-[min(96vw,1200px)] max-w-none sm:max-w-none md:max-w-[1200px] border-border/60 bg-panel text-foreground">
        {trade ? (
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={PANEL_TRANSITION}>
            <DialogHeader className="mb-6 space-y-2">
              <div className="flex items-start justify-between gap-4">
                <div className="space-y-3">
                  <DialogTitle className="text-2xl font-semibold tracking-tight">
                    {trade.instrument}
                  </DialogTitle>
                  <div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
                    <Badge
                      variant="secondary"
                      className={cn(
                        "rounded-full px-3",
                        trade.side === "Buy" ? "bg-primary/15 text-primary" : "bg-[color:var(--pilot-bad)]/15 text-[color:var(--pilot-bad)]",
                      )}
                    >
                      {trade.side}
                    </Badge>
                    <span>Notional {formatCurrency(trade.notional * 1_000_000)}</span>
                    <span className={profitTone}>Profit {formatCurrency(trade.profit)}</span>
                  </div>
                </div>
                <Button variant="ghost" onClick={() => onOpenChange(false)}>
                  Close
                </Button>
              </div>
              <DialogDescription className="text-xs uppercase tracking-[0.22em] text-muted-foreground">
                Trade lifecycle overview · fees auto-calculated at 3% split
              </DialogDescription>
            </DialogHeader>

            <div className="grid gap-6 md:grid-cols-[1.3fr_1fr]">
              <div className="space-y-4">
                <SectionCard title="Execution" helpText={sectionHelp.Execution}>
                  <DetailRow label="Entry Price" value={`$${formatDecimal(trade.entryPrice)}`} helpText={tradeMetricHelp["Entry Price"]} />
                  <DetailRow label="Exit Price" value={`$${formatDecimal(trade.exitPrice)}`} helpText={tradeMetricHelp["Exit Price"]} />
                  <DetailRow label="Entry Time" value={formatDate(trade.entryTime)} helpText={tradeMetricHelp["Entry Time"]} />
                  <DetailRow label="Exit Time" value={formatDate(trade.exitTime)} helpText={tradeMetricHelp["Exit Time"]} />
                  <DetailRow label="Duration" value={`${durationMinutes} minutes`} helpText={tradeMetricHelp.Duration} />
                </SectionCard>

                <SectionCard title="Participants" helpText={sectionHelp.Participants}>
                  {navigator ? (
                    <ParticipantRow
                      title="Navigator"
                      name={navigator.name}
                      score={navigator.pilotScore}
                    />
                  ) : null}
                  {pilot ? (
                    <ParticipantRow
                      title="Pilot"
                      name={pilot.name}
                      score={pilot.pilotScore}
                    />
                  ) : null}
                  {group ? (
                    <DetailRow label="Group" value={group.name} helpText={tradeMetricHelp.Group} />
                  ) : null}
                </SectionCard>
              </div>

              <div className="space-y-4">
                <SectionCard title="Fee Breakdown" helpText={sectionHelp["Fee Breakdown"]}>
                  <DetailRow label="Profit" value={formatCurrency(trade.profit)} tone={profitTone} helpText={tradeMetricHelp.Profit} />
                  <DetailRow label="3% Fee" value={formatCurrency(feePool)} helpText={tradeMetricHelp["3% Fee"]} />
                  <div className="mt-3 space-y-2 rounded-2xl border-2 border-border/40 bg-sidebar/40 p-3 text-xs">
                    <BreakdownRow label="Navigator (50%)" value={formatCurrency(navigatorFee)} />
                    <BreakdownRow label="Pilot (25%)" value={formatCurrency(pilotFee)} />
                    <BreakdownRow label="Broker (25%)" value={formatCurrency(brokerFee)} />
                  </div>
                </SectionCard>

                <SectionCard title="Risk & Compliance" helpText={sectionHelp["Risk & Compliance"]}>
                  <div className="flex items-center gap-2">
                    <Badge
                      variant="secondary"
                      className={cn(
                        "rounded-full px-3",
                        riskBadgeTone === "good"
                          ? "bg-primary/15 text-primary"
                          : "bg-[color:var(--pilot-bad)]/15 text-[color:var(--pilot-bad)]",
                      )}
                    >
                      {formatRiskFlag(trade.riskFlag)}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      {getRiskDescription(trade.riskFlag)}
                    </span>
                  </div>
                </SectionCard>

                <SectionCard title="Next Steps" helpText={sectionHelp["Next Steps"]}>
                  <p className="text-xs text-muted-foreground">
                    Price chart placeholder (future enhancement) · Recharts sparkline to visualise entry/exit more clearly.
                  </p>
                </SectionCard>
              </div>
            </div>
          </motion.div>
        ) : null}
      </DialogContent>
    </Dialog>
  );
}

function SectionCard({ title, children, helpText }: { title: string; children: React.ReactNode; helpText?: string }) {
  const card = (
    <div className="rounded-3xl border-2 border-border/50 bg-card/80 p-4">
      <div className="mb-3 text-xs uppercase tracking-[0.22em] text-muted-foreground">{title}</div>
      <div className="space-y-2 text-sm text-muted-foreground">{children}</div>
    </div>
  );

  return helpText ? (
    <HelpTooltip text={helpText} asChild>
      {card}
    </HelpTooltip>
  ) : card;
}

function ParticipantRow({ title, name, score }: { title: string; name: string; score: number }) {
  return (
    <div className="flex items-center justify-between rounded-2xl border-2 border-border/40 bg-sidebar/40 px-3 py-2 text-sm">
      <div className="flex items-center gap-3">
        <EntityAvatar name={name} className="h-8 w-8" />
        <div>
          <p className="font-medium text-foreground">{name}</p>
          <p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{title}</p>
        </div>
      </div>
      <ScoreBadge score={score} label="Score" />
    </div>
  );
}

function DetailRow({ label, value, tone, helpText }: { label: string; value: string; tone?: string; helpText?: string }) {
  const row = (
    <div className="flex items-center justify-between text-sm">
      <span className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{label}</span>
      <span className={cn("font-semibold text-foreground", tone)}>{value}</span>
    </div>
  );

  return helpText ? (
    <HelpTooltip text={helpText} asChild>
      {row}
    </HelpTooltip>
  ) : row;
}

function BreakdownRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-muted-foreground/80">{label}</span>
      <span className="font-semibold text-foreground">{value}</span>
    </div>
  );
}

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

export function formatRiskFlag(flag?: string | null) {
  switch (flag) {
    case "highLeverage":
      return "High leverage";
    case "oversized":
      return "Oversized";
    case "slippage":
      return "Slippage";
    case "cascade":
      return "Copy cascade";
    case "amlReview":
      return "AML review";
    case "none":
    case undefined:
    case null:
      return "None";
    default:
      return flag
        ?.split(/(?=[A-Z])/)
        .join(" ")
        .replace(/\b\w/g, (char) => char.toUpperCase()) ?? "None";
  }
}

function getRiskDescription(flag?: string | null) {
  switch (flag) {
    case "highLeverage":
      return "High leverage event flagged for compliance review.";
    case "oversized":
      return "Position size exceeded configured guardrails.";
    case "slippage":
      return "Slippage exceeded tolerance; monitor navigator alignment.";
    case "cascade":
      return "Copy cascade detected across linked accounts; verify throttles.";
    case "amlReview":
      return "Trade requires AML follow-up on source of funds.";
    case "none":
    case undefined:
    case null:
      return "No compliance flags triggered for this execution.";
    default:
      return "Risk flag triggered; review anomaly in compliance center.";
  }
}
