export const VALUE_BADGE_TOOLTIP =
  "Value to Broker combines this leader’s revenue, growth, and behaviour into a single score. High Value leaders generate strong revenue with healthier copier patterns.";

export const HELP_COPY = {
  modeToggle:
    "Switch between the Pilot-enabled view and a baseline scenario without copy trading to quantify uplift.",
  topNavigatorsTitle:
    "Shows your highest-value leaders based on revenue, growth, and behaviour to spotlight who drives the business.",
  topNavigatorRank:
    "Ranking by value to broker – rank 1 is currently your most commercially important leader.",
  navigatorConcentration:
    "Percentage of copy-trading revenue generated by your top three leaders. High concentration is a concentration risk if they churn.",
  copyTradingAnalyticsPage:
    "Product analytics for copy trading: funnel conversion, leader economics, follower behaviour, and blueprint sales.",
  alertsButton:
    "Open surveillance alerts to review compliance issues, AML triggers, or slippage anomalies in real time.",
} as const;
