"use client";

import Link from "next/link";
import { useMemo } from "react";
import {
  Area,
  AreaChart,
  ComposedChart,
  Line,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import type { Group, Navigator, Pilot } from "@/data/types";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { EntityAvatar } from "@/components/common/entity-avatar";
import { formatCurrency, formatNumber } from "@/lib/formatters";
import { cn } from "@/lib/utils";
import { HelpTooltip } from "@/components/help/help-tooltip";

interface NavigatorEconomicsViewProps {
  navigator: Navigator;
  groups: Group[];
  pilots: Pilot[];
}

const summaryHelpCopy = {
  brokerRevenue: "Broker revenue generated by this navigator in the last 30 days (fees and spread share).",
  navigatorRevenue: "What this navigator personally earned from followers over the last 30 days.",
  newCopiers: "Users who started copying this navigator within the past 30 days.",
  lostCopiers: "Copiers who churned or stopped copying this navigator in the last 30 days.",
  retention: "Percentage of this navigator’s copiers who remain active 30 days after they start copying.",
  growthRate: "Trailing 30-day revenue growth rate that highlights momentum for this navigator.",
} as const;

const navigatorFunnelHelp =
  "This funnel shows how effectively this navigator converts viewers into long-term copiers. Each drop-off highlights churn risk.";

const navigatorRevenueTrendHelp =
  "Shows how this navigator’s broker revenue has trended day by day so you can explain recent momentum.";

const navigatorVolumeChartHelp =
  "Compares copied volume with follower P&L to show whether this navigator is scaling healthy copier behaviour.";

const navigatorEconomicsTitleHelp =
  "Detailed revenue and follower analytics for this leader so you can explain exactly how valuable they are.";

const groupTableHelp = {
  group: "Navigator-aligned group name.",
  brokerRev: "Broker revenue this group produced over the last 30 days.",
  copiers: "Number of copiers assigned to the group.",
  retention: "Percent of group copiers still active after 30 days.",
  growth: "30-day growth rate for the group.",
} as const;

const followerTableHelp = {
  follower: "Pilot follower aligned to this navigator.",
  revenue: "Broker revenue this follower contributes.",
  daysActive: "How long the follower has been copying.",
  copyFreq: "Average copied trades per week.",
  profit: "Follower’s profit from copying this navigator.",
  ltv: "Lifetime revenue expected from this follower.",
} as const;

export function NavigatorEconomicsView({ navigator, groups, pilots }: NavigatorEconomicsViewProps) {
  const economics = navigator.navigatorEconomics;
  const copierStats = navigator.copierStats;

  const summaryCards = useMemo(() => {
    if (!economics) return [];
    return [
      {
        label: "Broker Revenue (30d)",
        value: economics.brokerRevenue30d,
        helpText: summaryHelpCopy.brokerRevenue,
      },
      {
        label: "Navigator Revenue (30d)",
        value: economics.navigatorRevenue30d,
        helpText: summaryHelpCopy.navigatorRevenue,
      },
      {
        label: "New Copiers (30d)",
        value: navigator.newCopiers30d ?? 0,
        helpText: summaryHelpCopy.newCopiers,
      },
      {
        label: "Lost Copiers (30d)",
        value: navigator.lostCopiers30d ?? 0,
        helpText: summaryHelpCopy.lostCopiers,
      },
      {
        label: "Retention 30d",
        value: navigator.retention30d ?? 0,
        unit: "%",
        helpText: summaryHelpCopy.retention,
      },
      {
        label: "Growth Rate",
        value: economics.growthRate30d,
        unit: "%",
        helpText: summaryHelpCopy.growthRate,
      },
    ];
  }, [economics, navigator.newCopiers30d, navigator.lostCopiers30d, navigator.retention30d]);

  const funnelStages = useMemo(() => {
    if (!copierStats) return [];
    const stages = [
      { label: "Registered", value: copierStats.registered, next: copierStats.firstCopy },
      { label: "First Copy", value: copierStats.firstCopy, next: copierStats.active },
      { label: "Active", value: copierStats.active, next: copierStats.retained30d },
      { label: "Retained 30d", value: copierStats.retained30d, next: 0 },
    ];
    return stages.map((stage) => ({
      ...stage,
      conversion: stage.next && stage.value ? Number(((stage.next / stage.value) * 100).toFixed(1)) : 0,
    }));
  }, [copierStats]);

  const chartData = useMemo(() => {
    const revenueTrend = navigator.revenueTrend?.length ? navigator.revenueTrend : navigator.trend.map((point) => point.value * 650);
    return revenueTrend.map((value, index) => {
      const volume = Math.round((navigator.groupVolume * 1_000_000) * (0.85 + index * 0.03));
      const pnl = Math.round(value * 0.18 + (index - 3) * 1_200);
      return {
        day: `Day ${index + 1}`,
        revenue: value,
        volume,
        pnl,
      };
    });
  }, [navigator.groupVolume, navigator.revenueTrend, navigator.trend]);

  const groupRows = useMemo(() => groups, [groups]);

  const followerRows = useMemo(() => {
    return [...pilots]
      .sort((a, b) => (b.pilotEconomics?.copierRevenueContributed ?? 0) - (a.pilotEconomics?.copierRevenueContributed ?? 0))
      .slice(0, 8);
  }, [pilots]);

  return (
    <div className="space-y-8">
      <header className="flex flex-col gap-4 rounded-3xl border-2 border-border/60 bg-sidebar/40 p-6 md:flex-row md:items-center md:justify-between">
        <div className="flex items-center gap-4">
          <EntityAvatar name={navigator.name} className="h-14 w-14" />
          <div>
            <HelpTooltip text={navigatorEconomicsTitleHelp} asChild indicator={false}>
              <p className="text-sm uppercase tracking-[0.24em] text-muted-foreground">Navigator Economics</p>
            </HelpTooltip>
            <h1 className="text-2xl font-semibold text-foreground">{navigator.name}</h1>
            <p className="text-sm text-muted-foreground">
              {formatNumber(navigator.followers)} followers · {formatCurrency(navigator.brokerRevenueShare)} broker rev / day
            </p>
          </div>
        </div>
        <Button asChild variant="outline" className="rounded-full border-border/60 bg-transparent text-sm">
          <Link href="/copy-trading/analytics">Back to analytics</Link>
        </Button>
      </header>

      {summaryCards.length ? (
        <section className="space-y-4">
          <h2 className="text-sm font-semibold uppercase tracking-[0.24em] text-muted-foreground">Economics Summary</h2>
          <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
            {summaryCards.map((card) => (
              <HelpTooltip key={card.label} text={card.helpText}>
                <div className="rounded-3xl border-2 border-border/60 bg-card/85 p-4">
                  <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">{card.label}</p>
                  <p className={cn("mt-2 text-2xl font-semibold", card.label.includes("Lost") && "text-[color:var(--pilot-bad)]") }>
                    {card.label.includes("Revenue")
                      ? formatCurrency(card.value)
                      : card.unit === "%"
                        ? `${card.value}%`
                        : formatNumber(card.value)}
                  </p>
                </div>
              </HelpTooltip>
            ))}
          </div>
        </section>
      ) : null}

      {funnelStages.length ? (
        <section className="space-y-4">
          <h2 className="text-sm font-semibold uppercase tracking-[0.24em] text-muted-foreground">Navigator Funnel</h2>
          <HelpTooltip text={navigatorFunnelHelp}>
            <div className="grid gap-4 md:grid-cols-4">
              {funnelStages.map((stage) => (
                <div key={stage.label} className="rounded-3xl border-2 border-border/50 bg-sidebar/40 p-4">
                  <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">{stage.label}</p>
                  <p className="mt-2 text-2xl font-semibold">{formatNumber(stage.value)}</p>
                  <p className="mt-2 text-xs text-muted-foreground">
                    {stage.conversion ? `${stage.conversion}% conversion` : "Retention anchor"}
                  </p>
                </div>
              ))}
            </div>
          </HelpTooltip>
        </section>
      ) : null}

      <section className="grid gap-4 lg:grid-cols-2">
        <HelpTooltip text={navigatorRevenueTrendHelp}>
          <Card className="rounded-3xl border-2 border-border/60 bg-card/85 shadow-none">
            <CardHeader>
              <CardTitle className="text-base font-semibold">Broker Revenue Trend</CardTitle>
              <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">Trailing 7 days</p>
            </CardHeader>
            <CardContent className="h-64 min-w-0">
              <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={220}>
                <AreaChart data={chartData} margin={{ top: 8, left: 0, right: 0, bottom: 0 }}>
                  <defs>
                    <linearGradient id="navigator-revenue" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#53f6c5" stopOpacity={0.6} />
                      <stop offset="95%" stopColor="#53f6c5" stopOpacity={0.05} />
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: "#7c8aa6" }} />
                  <YAxis hide domain={[0, "auto"]} />
                  <Tooltip
                    contentStyle={tooltipStyles}
                    formatter={(value: number) => [formatCurrency(value), "Revenue"]}
                  />
                  <Area type="monotone" dataKey="revenue" stroke="#53f6c5" strokeWidth={2} fill="url(#navigator-revenue)" />
                </AreaChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </HelpTooltip>

        <HelpTooltip text={navigatorVolumeChartHelp}>
          <Card className="rounded-3xl border-2 border-border/60 bg-card/85 shadow-none">
            <CardHeader>
              <CardTitle className="text-base font-semibold">Copied Volume & Follower P&L</CardTitle>
              <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">Volume vs economics</p>
            </CardHeader>
            <CardContent className="h-64 min-w-0">
              <ResponsiveContainer width="100%" height="100%" minWidth={0} minHeight={220}>
                <ComposedChart data={chartData} margin={{ top: 8, left: 0, right: 0, bottom: 0 }}>
                  <XAxis dataKey="day" tickLine={false} axisLine={false} tick={{ fill: "#7c8aa6" }} />
                  <YAxis yAxisId="left" hide domain={[0, "auto"]} />
                  <YAxis yAxisId="right" orientation="right" hide domain={[0, "auto"]} />
                  <Tooltip
                    contentStyle={tooltipStyles}
                    formatter={(value: number, name) => [
                      formatCurrency(value),
                      name === "pnl" ? "Follower P&L" : "Copied Volume",
                    ]}
                  />
                  <Area yAxisId="left" type="monotone" dataKey="volume" stroke="#51e5ff" fill="rgba(81,229,255,0.25)" strokeWidth={2} />
                  <Line yAxisId="right" type="monotone" dataKey="pnl" stroke="#f472b6" strokeWidth={2} dot={false} />
                </ComposedChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>
        </HelpTooltip>
      </section>

      <section className="grid gap-4 lg:grid-cols-2">
        <Card className="rounded-3xl border-2 border-border/60 bg-card/85 shadow-none">
          <CardHeader>
            <CardTitle className="text-base font-semibold">Group-Level Economics</CardTitle>
            <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">Navigator-aligned groups</p>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow className="border-border/40">
                  <TableHead>
                    <HelpTooltip text={groupTableHelp.group} asChild indicator={false}>
                      <span>Group</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={groupTableHelp.brokerRev} asChild indicator={false}>
                      <span>Broker Rev 30d</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={groupTableHelp.copiers} asChild indicator={false}>
                      <span>Copiers</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={groupTableHelp.retention} asChild indicator={false}>
                      <span>Retention</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={groupTableHelp.growth} asChild indicator={false}>
                      <span>Growth</span>
                    </HelpTooltip>
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {groupRows.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={5} className="py-6 text-center text-sm text-muted-foreground">
                      No group economics available yet.
                    </TableCell>
                  </TableRow>
                ) : null}
                {groupRows.map((group) => (
                  <TableRow key={group.id} className="border-border/10">
                    <TableCell className="font-semibold text-foreground">{group.name}</TableCell>
                    <TableCell>{group.groupEconomics ? formatCurrency(group.groupEconomics.brokerRevenue30d) : "—"}</TableCell>
                    <TableCell>{group.groupEconomics ? formatNumber(group.groupEconomics.copiers) : "—"}</TableCell>
                    <TableCell>{group.groupEconomics ? `${group.groupEconomics.retention30d}%` : "—"}</TableCell>
                    <TableCell>{group.groupEconomics ? `${group.groupEconomics.growthRate30d}%` : "—"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>

        <Card className="rounded-3xl border-2 border-border/60 bg-card/85 shadow-none">
          <CardHeader>
            <CardTitle className="text-base font-semibold">Top Followers</CardTitle>
            <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">Navigator-aligned pilots</p>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow className="border-border/40">
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.follower} asChild indicator={false}>
                      <span>Follower</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.revenue} asChild indicator={false}>
                      <span>Revenue Contrib.</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.daysActive} asChild indicator={false}>
                      <span>Days Active</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.copyFreq} asChild indicator={false}>
                      <span>Copy Freq</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.profit} asChild indicator={false}>
                      <span>Copier Profit</span>
                    </HelpTooltip>
                  </TableHead>
                  <TableHead>
                    <HelpTooltip text={followerTableHelp.ltv} asChild indicator={false}>
                      <span>LTV</span>
                    </HelpTooltip>
                  </TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {followerRows.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className="py-6 text-center text-sm text-muted-foreground">
                      No follower economics for this navigator.
                    </TableCell>
                  </TableRow>
                ) : null}
                {followerRows.map((pilot) => (
                  <TableRow key={pilot.id} className="border-border/10">
                    <TableCell className="font-semibold text-foreground">{pilot.name}</TableCell>
                    <TableCell>{pilot.pilotEconomics ? formatCurrency(pilot.pilotEconomics.copierRevenueContributed) : "—"}</TableCell>
                    <TableCell>{pilot.pilotEconomics ? pilot.pilotEconomics.daysActive : "—"}</TableCell>
                    <TableCell>{pilot.pilotEconomics ? `${pilot.pilotEconomics.copyFrequency}/wk` : "—"}</TableCell>
                    <TableCell className={cn(pilot.pilotEconomics && pilot.pilotEconomics.copierProfit < 0 && "text-[color:var(--pilot-bad)]")}>{
                      pilot.pilotEconomics ? formatCurrency(pilot.pilotEconomics.copierProfit) : formatCurrency(pilot.profit)
                    }</TableCell>
                    <TableCell>{pilot.pilotEconomics ? formatCurrency(pilot.pilotEconomics.lifetimeValue) : "—"}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </section>
    </div>
  );
}

const tooltipStyles = {
  backgroundColor: "rgba(5,12,28,0.95)",
  borderRadius: 12,
  border: "1px solid rgba(83,246,197,0.2)",
  color: "white",
};
