"use client";

import { useMemo } from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { EntityAvatar } from "@/components/common/entity-avatar";
import { ValueBadge } from "@/components/common/value-badge";
import { formatCurrency, formatNumber } from "@/lib/formatters";
import { getNavigatorEconomicsLeaderboardRows } from "@/lib/aggregations";
import { HelpTooltip } from "@/components/help/help-tooltip";
import { VALUE_BADGE_TOOLTIP } from "@/components/help/help-text";

const columnHelp = {
  brokerRevenue30d:
    "Total broker revenue generated by this navigator over the last 30 days (fees and spreads from their copied trades).",
  newCopiers30d:
    "Number of new copiers who started following this navigator in the last 30 days.",
  lostCopiers30d:
    "Number of copiers who stopped copying this navigator in the last 30 days.",
  retention30d:
    "Percentage of copiers who are still copying this navigator 30 days after starting.",
  avgLifetime:
    "Average number of days a copier stays with this navigator before stopping.",
  avgRevenue:
    "Average broker revenue generated by each follower of this navigator.",
} as const;

export function NavigatorEconomicsLeaderboard() {
  const router = useRouter();
  const rows = useMemo(() => getNavigatorEconomicsLeaderboardRows(), []);

  return (
    <Card className="rounded-3xl border-2 border-border/60 bg-card/85 shadow-none">
      <CardHeader className="flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
        <div>
          <CardTitle className="text-base font-semibold">Navigator Economics Leaderboard</CardTitle>
          <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">Ranked by ValueScore</p>
        </div>
        <p className="text-xs text-muted-foreground/80">Tap a row to open detailed economics</p>
      </CardHeader>
      <CardContent className="p-0">
        <Table>
          <TableHeader>
            <TableRow className="border-border/40">
              <TableHead className="w-[20%]">Navigator</TableHead>
              <TableHead>ValueScore</TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.brokerRevenue30d}>
                  <span>Broker Rev 30d</span>
                </HelpTooltip>
              </TableHead>
              <TableHead>Total Copiers</TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.newCopiers30d}>
                  <span>New 30d</span>
                </HelpTooltip>
              </TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.lostCopiers30d}>
                  <span>Lost 30d</span>
                </HelpTooltip>
              </TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.retention30d}>
                  <span>Retention 30d</span>
                </HelpTooltip>
              </TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.avgLifetime}>
                  <span>Lifetime (days)</span>
                </HelpTooltip>
              </TableHead>
              <TableHead>
                <HelpTooltip text={columnHelp.avgRevenue}>
                  <span>Avg Copier Revenue</span>
                </HelpTooltip>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.map((row) => (
              <TableRow
                key={row.id}
                className="cursor-pointer border-border/20 transition hover:bg-primary/5"
                onClick={() => router.push(`/copy-trading/navigators/${row.id}/economics`)}
              >
                <TableCell className="flex items-center gap-3">
                  <EntityAvatar name={row.name} className="h-9 w-9" />
                  <div>
                    <p className="font-semibold text-foreground">{row.name}</p>
                    {row.valueTier ? (
                      <HelpTooltip text={VALUE_BADGE_TOOLTIP}>
                        <ValueBadge tier={row.valueTier} label={row.valueLabel ?? row.valueTier} />
                      </HelpTooltip>
                    ) : null}
                  </div>
                </TableCell>
                <TableCell className="font-semibold text-foreground">{row.valueScore.toFixed(0)}</TableCell>
                <TableCell>{formatCurrency(row.brokerRevenue30d)}</TableCell>
                <TableCell>{formatNumber(row.totalCopiers)}</TableCell>
                <TableCell className="text-primary">{formatNumber(row.newCopiers30d)}</TableCell>
                <TableCell className="text-[color:var(--pilot-bad)]">{formatNumber(row.lostCopiers30d)}</TableCell>
                <TableCell>{row.retention30d}%</TableCell>
                <TableCell>{row.avgCopierLifetimeDays}</TableCell>
                <TableCell>{formatCurrency(row.avgCopierRevenue)}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
